src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_Check_OK__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vehicle Check OK</label>
        <type>Checkbox</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vehicle_Check__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Vehicle Checks</relationshipLabel>
        <relationshipName>Vehicle_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle Check</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>Vehicle Check No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VehicleCheckTriggerMethods.cls
/*
* 2014-02-11 : SM : This class is used to hold any methods called from the Vehicle_Check__c trigger
*/
public with sharing class VehicleCheckTriggerMethods {

	public static final String STATUS_ACTIVE = 'Active';
	
	//This method will update the 'Vehicle_Check_OK__c' field on the corresponding Application__c record if the Vehicle Check status is Active
	public static void updateApplication(List<Vehicle_Check__c> inRecords){
		Set<Id> appIds = new Set<Id>();
		List<Application__c> appsToSave = new List<Application__c>(); 
		for (Vehicle_Check__c vc : inRecords){
			appIds.add(vc.Role__c);
		}
		
		Map<Id, Application__c> appMap = new Map<Id, Application__c>([select a.Id, a.Vehicle_Check_OK__c from Application__c a where a.Id in :appIds]);
		
		for (Vehicle_Check__c vc : inRecords){
			if (STATUS_ACTIVE.equalsIgnoreCase(vc.Status__c)){
				Application__c theApp = appMap.get(vc.Role__c);
				if (theApp != null){
					theApp.Vehicle_Check_OK__c = true;
					appsToSave.add(theApp);
				}
			}
		}
		
		if (appsToSave.size() > 0){
			update appsToSave;
		}
	}
	
}