src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <formula>&quot;See Opportunity Record&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <formula>Role__r.Role_Title__c</formula>
        <label>Role Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Role</fullName>
        <active>true</active>
        <description>This record type is when somebody is fulfilling a role or inactive in a role they were previously doing</description>
        <label>Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
</CustomObject>

src/objects/Risk_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <formula>IF(INCLUDES(  Application__r.Role__r.Location__c  , &quot;North West&quot;), &quot;North West&quot; + BR() , NULL) +
IF(INCLUDES(  Application__r.Role__r.Location__c  , &quot;North East&quot;), &quot;North East&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;South West&quot;), &quot;South West&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;South East&quot;), &quot;South East&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;West Midlands&quot;), &quot;West Midlands&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;East Midlands&quot;), &quot;East Midlands&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;London&quot;), &quot;London&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;East of England&quot;), &quot;East of England&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;Yorkshire/Humber&quot;), &quot;Yorkshire/Humber&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;Scotland&quot;), &quot;Scotland&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;Wales&quot;), &quot;Wales&quot; + BR() , NULL) +
IF(INCLUDES( Application__r.Role__r.Location__c , &quot;Northern Ireland&quot;), &quot;Northern Ireland&quot;, NULL)</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Risk_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Criminal Record Check</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Criminal Record Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criminal Record Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Active_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DBS_Check_required__c</fullName>
        <label>Criminal Record Check Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Access NI Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults and Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Check Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>today()+180</defaultValue>
        <inlineHelpText>This is the date that the opportunity is closed.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_per_week__c</fullName>
        <inlineHelpText>Indicate the estimated number of hours per week the volunteers will be needed</inlineHelpText>
        <label>How Many Hours A Week Are You Needed?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>DBS_Check_required__c</controllingField>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East of England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire/Humber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Number_of_References_Required__c</fullName>
        <inlineHelpText>Enter the number of references required in order to successfully apply for this role</inlineHelpText>
        <label>Number of References Required</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <inlineHelpText>Describe the Purpose and Aims of the role in a short, punchy paragraph.</inlineHelpText>
        <label>Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_involve_working_with_Children__c</fullName>
        <label>Role Involves Working With Children?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <inlineHelpText>This is required for services like TSS</inlineHelpText>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_support_will_I_be_given__c</fullName>
        <inlineHelpText>Enter the support which the Volunteers will be provided here</inlineHelpText>
        <label>What Support Will You Be Given?</label>
        <picklist>
            <picklistValues>
                <fullName>Understanding Sight Loss Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Induction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervision &amp; Support from your Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular updates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training as appropriate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sighted Guiding Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support from Volunteers &amp; Staff</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>What_will_I_be_doing__c</fullName>
        <inlineHelpText>Choose from pick list above or type into text box. Please do not use more than five bullet points in total</inlineHelpText>
        <label>What Will You Be Doing - Further Info</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>What_will_I_gain_from_the_role__c</fullName>
        <inlineHelpText>Please bullet list (MAXIMUM of 5) the key things that will be gained (for example, meeting new friends, working in a customer facing environment, etc)</inlineHelpText>
        <label>What Will You Gain from the Role?</label>
        <picklist>
            <picklistValues>
                <fullName>A chance to give something back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A chance to make a difference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experience in a care setting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experience of fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working in an office environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working with a variety of people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working with people with sight loss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working with older people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working with young people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting new people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New experiences and skills</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard volunteer opportunities (e.g. Admin, Befriending, Campaigning, CYF, ECLO, Fundraising, Technology, etc.)</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleDetailsControllerTest.cls
@isTest (seeAllData=true)
private class RoleDetailsControllerTest {

   static testMethod void testgetRoleDetails(){
   
   date enddate = date.today().addDays(30);
      
      Role_Opportunity__c testRole = new Role_Opportunity__c();
      testRole.Role_Title__c = 'firstname';
      testRole.Location__c = 'lastname';
      testRole.End_Date__c = enddate;
     testRole.Role_Description__c = 'Role Description';
      testRole.What_will_I_be_doing__c ='Doing Something';
      testRole.Hours_per_week__c = 10;
    //  testRole.What_will_I_gain_from_the_role__c = 'Gain';
      testRole.What_support_will_I_be_given__c ='Induction';
      testRole.DBS_Check_required__c = 'DBS Standard';
      testRole.Number_of_References_Required__c = '2';
      
      insert testRole;
    
     PageReference ref = new PageReference('/apex/Role_Details?id=' + testRole.id); 
     test.setCurrentPage(ref);

      RoleDetailsController controller = new RoleDetailsController();
     controller.getRoleDetails();
      
 
  }


static testMethod void testgetRoleDetailsWithApplications(){
   Profile saProfile = [select p.Id from Profile p where Name = 'System Administrator' LIMIT 1];
    Profile vProfile = [select p.Id from Profile p where Name = 'Community Login User - Volunteers' LIMIT 1];
    List<User>userList = [select u.Id from User u where u.IsActive = true and u.ProfileId = :saProfile.Id LIMIT 2];
    List<User>volunteerList = [select u.Id, u.ContactId from User u where u.ProfileId = :vProfile.Id and IsActive = true];
    Contact volunteerContact = TestUtilities.getContactRecord(volunteerList[0].ContactId);
    if (volunteerContact.FirstName == null) volunteerContact.FirstName = 'Test';
    if (volunteerContact.LastName == null) volunteerContact.LastName = 'Contact';
    if (volunteerContact.Email == null) volunteerContact.Email = volunteerContact.FirstName.toLowerCase() + '.' + volunteerContact.LastName.toLowerCase() + '@myemail.com';
    if (volunteerContact.MailingStreet == null) volunteerContact.MailingStreet = '123 Fake Street';
    if (volunteerContact.MailingCity == null) volunteerContact.MailingCity = 'London';
    if (volunteerContact.MailingState == null) volunteerContact.MailingState = 'London';
    if (volunteerContact.MailingPostalCode == null) volunteerContact.MailingPostalCode = 'EC12 1PR';
    if (volunteerContact.Phone == null) volunteerContact.Phone = '02071111111';
    update volunteerContact;
    
    User volunteerMgr = userList[0];
    User volunteerCoord = userList[1];
    RecordType standardRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_STANDARD);
    Role_Opportunity__c roleOpp = TestUtilities.getRoleOpportunity(TestUtilities.RT_STANDARD, standardRT.Id);
    roleOpp.Volunteer_Manager__c = volunteerMgr.Id;
    roleOpp.Volunteer_Coordinator__c = volunteerCoord.Id;
    roleOpp.Role_involve_working_with_Children__c = 'No';
    roleOpp.Number_of_References_Required__c = '2';
    roleOpp.Active_on_Website__c = true;
    roleOpp.Status__c = 'Approved';
    roleOpp.DBS_Check_required__c = 'DBS Standard';
    roleOpp.Vehicle_Check_Required__c = true;
    roleOpp.Risk_Assessment__c = true; 
    insert roleOpp;
    
    
    RecordType appRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_APPLICATION);
    Application__c application = new Application__c(RecordTypeId = appRT.Id);
    
    application.Applicant__c = volunteerContact.Id;
    application.Role__c = roleOpp.Id;
    
    insert application;
   
        
    test.startTest();
    
    system.runAs(volunteerList[0]){
    
	    PageReference ref = new PageReference('/apex/Role_Details?id=' + roleOpp.id); 
    	test.setCurrentPage(ref);

	    RoleDetailsController controller = new RoleDetailsController();
    	controller.getRoleDetails();
    	
    }
    
    test.stopTest();
 
  }


   static testMethod void testgetRoleDetailsNull(){
  
   
     PageReference ref = new PageReference('/apex/Role_Details'); 
     test.setCurrentPage(ref);

     RoleDetailsController controller = new RoleDetailsController();
     controller.getRoleDetails();

  }

}