src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <formula>&quot;See Opportunity Record&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <formula>Role__r.Role_Title__c</formula>
        <label>Role Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <picklist>
            <picklistValues>
                <fullName>Ability to engage with older people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to engage with young people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Able to work on your own initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confident people skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confident public Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enthusiastic and confident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good administrative skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good IT skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good listening and communication skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good organisational skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Telephone skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge of access technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sensitive and empathetic to others</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Ability_to_follow_policies_and_procedure__c</fullName>
        <label>Ability to follow policies &amp; procedures:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ability_to_perform_role__c</fullName>
        <label>Ability to perform role:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Referee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Further_Comments__c</fullName>
        <label>Further Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Honesty_integrity_Ability_to_maintain_co__c</fullName>
        <label>Honesty/integrity/Ability to maintain co</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>How_long_have_you_known_the_above_named__c</fullName>
        <label>How long have you known the above named</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_what_capacity_do_you_know_this_person__c</fullName>
        <label>In what capacity do you know this person</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommend_To_RNIB_Comments__c</fullName>
        <label>Recommend To RNIB Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommend_To_RNIB__c</fullName>
        <label>Recommend To RNIB</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reference Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationships_with_others__c</fullName>
        <label>Relationships with others:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reliability__c</fullName>
        <label>Reliability:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <formula>Application__r.Role_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <formula>Application__r.Role_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suitable_to_Volunteer_with_Children__c</fullName>
        <inlineHelpText>Are you satisfied that this person is suitable to volunteer with children, if not, please give details</inlineHelpText>
        <label>Suitable to Volunteer with Children?</label>
        <type>TextArea</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>Reference - {0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Role_Description__c</fullName>
        <inlineHelpText>Describe the Purpose and Aims of the role in a short, punchy paragraph.</inlineHelpText>
        <label>Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_will_I_be_doing2__c</fullName>
        <description>This one is the pick list the other is free form text</description>
        <inlineHelpText>Enter information about the expected activities of Volunteers</inlineHelpText>
        <label>What Will You Be Doing?</label>
        <picklist>
            <controllingField>Opportunity_Family__c</controllingField>
            <picklistValues>
                <fullName>Assist with a variety of admin tasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Answering and making telephone calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintain records and computer files</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create documents and input data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting and greeting visitors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provide sighted guiding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone clients and customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respond to questions and concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurately record information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Using IT equipment and systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listen to Talk and Support group talks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Making appropriate contributions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create a friendly welcome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Link between group and staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit people in their home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Having a chat and providing company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read mail, magazines, etc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assisting with personal correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help set up and run activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Making teas and coffees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acting as a sighted guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan and action local campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build local links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keeping supporters abreast of campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help organise campaign events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publicising agreed campaigns.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accompany coordinators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assist with paperwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assist in accessing public transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving coordinators to and from events</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>What_will_I_be_doing__c</fullName>
        <inlineHelpText>Choose from pick list above or type into text box. Please do not use more than five bullet points in total</inlineHelpText>
        <label>What Will You Be Doing - Further Info</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReferenceFormController.cls
public class ReferenceFormController {
	public final String REF_ID_PARAM = 'id';
	public final String CHILD_FLAG_PARAM = 'c';
	public final String MESSAGE_PARAM = 'm';
	public final String THANKYOU_MESSAGE = 'THANKYOU';
	public final String ALREADY_SUBMITTED_MESSAGE = 'ALREADYSUBMITTED';
	public Reference__c theReference {get; set;}
	public Role_Opportunity__c theRole {get; set;}
	public PageReference thankyouPage {get; set;}
	public boolean showAlreadySubmitted {get; set;}
	public boolean showThankyou {get; set;}
	public boolean showChildQuestion {get; set;}
	

	public ReferenceFormController(ApexPages.StandardController std){
		String whichMessage = ApexPages.currentPage().getParameters().get(MESSAGE_PARAM);
		String forChildren = ApexPages.currentPage().getParameters().get(CHILD_FLAG_PARAM);
		
		if (whichMessage != null){
			if (THANKYOU_MESSAGE.equalsIgnoreCase(whichMessage)){
				showThankyou = true;
				showAlreadySubmitted = false;
			}else if (ALREADY_SUBMITTED_MESSAGE.equalsIgnoreCase(whichMessage)){
				showThankyou = false;
				showAlreadySubmitted = true;
			}
		}
		
		if ('NO'.equalsIgnoreCase(forChildren)){
			showChildQuestion = false;
		}else {
			showChildQuestion = true;
		}
		
		Id refId = ApexPages.currentPage().getParameters().get(REF_ID_PARAM);
		
		if (refId != null){
			
			theReference = [Select r.Reference_Received__c, r.Application__r.Applicant__r.FirstName, r.Application__r.Applicant__r.LastName, r.Contact__r.Name, r.Contact__r.FirstName, r.Contact__r.LastName, 
							r.Contact__r.MailingStreet, r.Contact__r.MailingCity, r.Contact__r.MailingState, 
							r.Contact__r.MailingPostalCode,	r.Recommend_To_RNIB__c, r.Contact__r.Email, r.Contact__r.Phone, 
							r.Recommend_To_RNIB_Comments__c, r.Further_Comments__c, r.Reliability__c, r.Relationships_with_others__c, r.In_what_capacity_do_you_know_this_person__c, 
							r.How_long_have_you_known_the_above_named__c, r.Honesty_integrity_Ability_to_maintain_co__c, r.Ability_to_perform_role__c, 
							r.Ability_to_follow_policies_and_procedure__c, r.Suitable_to_Volunteer_with_Children__c,
							r.Application__r.Role_Title__c, r.Application__r.Role_Description__c, r.Application__r.Role__r.What_will_I_be_doing2__c,
							r.Application__r.Role__r.What_will_I_be_doing__c, r.Application__r.Role__r.Skills__c From Reference__c r where r.Id = :refId];
							
		}			
	
				
	}
	
	public PageReference doSubmit(){
		PageReference returnPage;
		if (theReference != null){
			theReference.Reference_Received__c = true;
			update theReference;
		}
		returnPage = Page.ReferenceThankyou;
		returnPage.getParameters().put(MESSAGE_PARAM, THANKYOU_MESSAGE);
		returnPage.setRedirect(true);
		return returnPage;
	}
	
	public PageReference checkForSubmitted(){
		PageReference thankyouPage = Page.ReferenceThankyou;
		if (theReference != null){
			if (theReference.Reference_Received__c){
				thankyouPage.getParameters().put(MESSAGE_PARAM, ALREADY_SUBMITTED_MESSAGE);
				thankyouPage.setRedirect(true);
				return thankyouPage;		
			}else{
				return null;	
			}
		}
		return null;
		
	}

}