src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Criminal_Check_OK__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Criminal Check OK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>On_Update_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has the volunteer signed up to the update service?</inlineHelpText>
        <label>On Update Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Risk_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Risk_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>On_Update_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check this box if the volunteer has signed up to the update service - Note: this will also update the update service status on the volunteer&apos;s contact record</inlineHelpText>
        <label>On Update Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Witnesses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Counter Signatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Authorities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Checked - Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Approved - Need Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Criminal Record Checks</relationshipLabel>
        <relationshipName>Risk_Assessments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Criminal Record Check</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Criminal Record Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criminal Record Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RiskAssesmentTriggerClass.cls
/*
* 2014-02-11 : SM : This class is used to hold any methods called from the Risk_Assessment__c trigger
*/
public class RiskAssesmentTriggerClass {

	public static final String STATUS_APPROVED = 'Approved';
	public static final String STATUS_CERTIFICATE_APPROVED = 'Certificate Approved';
	
	//This method will update the corresponding Contact record if the check box On_Update_Service is ticked / unticked
	public static void updateOnUpdateService(List<Risk_Assessment__c> inRecords){
		Set<Id> contactIds = new Set<Id>();
		List<Contact> contactsToSave = new List<Contact>();
		
		for (Risk_Assessment__c ra : inRecords){
			contactIds.add(ra.Volunteer__c);
		}
		
		Map<Id, Contact> contactMap = new Map<Id, Contact>([select c.Id, c.On_Update_Service__c from Contact c where c.Id in :contactIds]);
		
		for (Risk_Assessment__c ra : inRecords){
			Contact c = contactMap.get(ra.Volunteer__c);
			if (c != null){
				c.On_Update_Service__c = ra.On_Update_Service__c;
				contactsToSave.add(c);
			}
		}
		
		update contactsToSave;
		
	}
	
	//This method will update the 'Criminal_Check_OK__c' field on the corresponding Application__c record if the Risk Assessment status is Approved
	public static void updateApplication(List<Risk_Assessment__c> inRecords){
		Set<Id> appIds = new Set<Id>();
		List<Application__c> appsToSave = new List<Application__c>(); 
		for (Risk_Assessment__c ra : inRecords){
			appIds.add(ra.Application__c);
		}
		
		Map<Id, Application__c> appMap = new Map<Id, Application__c>([select a.Id, a.Criminal_Check_OK__c from Application__c a where a.Id in :appIds]);
		
		for (Risk_Assessment__c ra : inRecords){
			if (STATUS_APPROVED.equalsIgnoreCase(ra.Status__c) || STATUS_CERTIFICATE_APPROVED.equalsIgnoreCase(ra.Status__c)){
				Application__c theApp = appMap.get(ra.Application__c);
				if (theApp != null){
					theApp.Criminal_Check_OK__c = true;
					appsToSave.add(theApp);
				}
			}
		}
		
	}

}