src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Role</fullName>
        <active>true</active>
        <description>This record type is when somebody is fulfilling a role or inactive in a role they were previously doing</description>
        <label>Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Use this record type for the volunteer</description>
        <label>Volunteer</label>
    </recordTypes>
</CustomObject>

src/objects/Expense_Form__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Expense Forms</relationshipLabel>
        <relationshipName>Expense_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Form</label>
    <nameField>
        <displayFormat>EXPENSE FORM-{00000}</displayFormat>
        <label>Expense Form No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Donation__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Donation</label>
    <nameField>
        <label>Time Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Donations</pluralLabel>
    <recordTypes>
        <fullName>Individual_Time_Donation</fullName>
        <active>true</active>
        <description>Use this record type to create Time Donations for Individuals</description>
        <label>Individual Customer Time Donation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestExpenseFormController.cls
/**
* 2014-04-04 : SM : This is the test class for ExpenseFormController
*/
@isTest(SeeAllData=true)
private class TestExpenseFormController {

    static testMethod void testController() {
    	RecordType volunteerRT = [select r.Id from RecordType r where r.DeveloperName = 'Volunteer' and r.SObjectType = 'Contact' LIMIT 1];
    	RecordType roleRT = [select r.Id from RecordType r where r.DeveloperName = 'Role' and r.SObjectType = 'Application__c' LIMIT 1];
    	RecordType tdRT = [select r.Id from RecordType r where r.DeveloperName = 'Individual_Time_Donation' and r.SObjectType = 'Time_Donation__c' LIMIT 1];
    	
        //We need to get the data we need and run as the right user
        Application__c application = [select a.Id, a.Applicant__c from Application__c a where a.RecordTypeId = :roleRT.Id and a.Status__c = 'Active' ORDER BY CreatedDate DESC LIMIT 1];
        User applicantUser = [select u.Id, u.ContactId from User u where u.ContactId = :application.Applicant__c LIMIT 1];
        
        PageReference testPage = Page.ExpenseForm;
        
        test.setCurrentPage(testPage);
        
        Expense_Form__c expenseForm = new Expense_Form__c();	
        expenseForm.Volunteer_Role__c = application.Id;
        expenseForm.Date__c = Date.today();
        
        ApexPages.StandardController std = new ApexPages.StandardController(expenseForm);
        ExpenseFormController controller = new ExpenseFormController(std);
        
        PageReference savePage = controller.saveAndNew(); 
        
        system.runAs(applicantUser){
        	PageReference testPage1 = Page.ExpenseForm;
        
	        test.setCurrentPage(testPage1);
	        
	        Expense_Form__c expenseForm1 = new Expense_Form__c();	
	        expenseForm1.Volunteer_Role__c = application.Id;
	        expenseForm1.Date__c = Date.today();
	        
	        ApexPages.StandardController std1 = new ApexPages.StandardController(expenseForm1);
	        ExpenseFormController controller1 = new ExpenseFormController(std1);
	        
	        PageReference savePage1 = controller1.saveAndNew();
        }
        
    }
}