src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApplicationExpiry.cls
/*
* 2014-03-06 : SM : This class is scheduled by ScheduledApplicationExpiry, to search for Applications
* that have not neen modified for the last seven days, and are in status of DRAFT
*/
public class ApplicationExpiry {
    public final String STATUS_DRAFT = 'Draft';
    public final String STATUS_INCOMPLETE = 'Incomplete';

    public ApplicationExpiry(){
        List<Application__c> appsToSave = new List<Application__c>();
        List<Application__c> checkApplications = new List<Application__c>();
        Date expiryDate = Date.today().addDays(-7);
        
        if (test.isRunningTest()){
            checkApplications = [select a.Id, a.LastModifiedDate, a.Status__c 
                                                    From Application__c a where a.CreatedDate = TODAY
                                                    and a.Status__c = :STATUS_DRAFT];   
        }else {
            checkApplications = [select a.Id, a.LastModifiedDate, a.Status__c 
                                                    From Application__c a where a.LastModifiedDate >= : expiryDate
                                                    and a.Status__c = :STATUS_DRAFT];
        }
        
        for (Application__c a : checkApplications){
            a.Status__c = STATUS_INCOMPLETE;
            appsToSave.add(a);
        }
        
        update appsToSave;
        
    }
}