src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>A person that has made one or more customer requests</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/CR_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Request__c</fullName>
        <label>Customer Request</label>
        <referenceTo>Customer_Requests__c</referenceTo>
        <relationshipLabel>Customer Request Notifications</relationshipLabel>
        <relationshipName>Customer_Request_Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Notification_Sent__c</fullName>
        <label>Date Notification Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Responded__c</fullName>
        <label>Date Responded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted but no longer available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Request Notifications</relationshipLabel>
        <relationshipName>Customer_Request_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Request Notification</label>
    <nameField>
        <displayFormat>CRN-{00000}</displayFormat>
        <label>Customer Request Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Request Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Requests__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_Volunteer__c</fullName>
        <description>Lookup field to hold the assigned volunteer (community user) for the Customer Request</description>
        <label>Assigned Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Requests (Assigned Volunteer)</relationshipLabel>
        <relationshipName>Assigned_Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - See RNIB Comments Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Customer Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Risk_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Witnesses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Counter Signatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Authorities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Checked - Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Approved - Need Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Risk_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Criminal Record Checks</relationshipLabel>
        <relationshipName>Risk_Assessments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Criminal Record Check</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Criminal Record Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criminal Record Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Active_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_References_Required__c</fullName>
        <inlineHelpText>Enter the number of references required in order to successfully apply for this role</inlineHelpText>
        <label>Number of References Required</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role_involve_working_with_Children__c</fullName>
        <label>Role Involves Working With Children?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent for approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <inlineHelpText>This is required for services like TSS</inlineHelpText>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard volunteer opportunities (e.g. Admin, Befriending, Campaigning, CYF, ECLO, Fundraising, Technology, etc.)</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerRequestResponseController.cls
global class CustomerRequestResponseController {
    global String whichAction {get; set;}
    global Id customerRequestId {get; set;}
    global Id volunteerId {get; set;}
    global boolean alreadyAccepted {get; set;}
    global boolean doAcceptedForward {get; set;}
    global boolean showRejected {get; set;}
    global String openRequestURL {get; set;}
    global final String ACTION_PARAM = 'ACTION';
    global final String ID_PARAM = 'CR';
    global final String VOLUNTEER_ID = 'V';
    global final String RESPONSE_ACCEPT = 'Accept';
    global final String RESPONSE_REJECT = 'Reject';
    global final String RT_CUSTOMER_REQUEST_PORTAL = 'Customer Requests - Portal';
    global final String CRN_STATUS_ACCEPTED = 'Accepted';
    global final String CRN_STATUS_ACCEPTED_NOT_AVAILABLE = 'Accepted but no longer available';
    global final String CRN_STATUS_REJECTED = 'Rejected';
    //Change this URL for TEST / LIVE as approproate
    //global final String PORTAL_URL = 'https://uat-rnib-community-uat.cs17.force.com/';
    global final String PORTAL_URL = 'https://rnib.force.com/';

    global CustomerRequestResponseController(){
        whichAction = ApexPages.currentPage().getParameters().get(ACTION_PARAM);
        customerRequestId = ApexPages.currentPage().getParameters().get(ID_PARAM);
        volunteerId = ApexPages.currentPage().getParameters().get(VOLUNTEER_ID);
        alreadyAccepted = false;
        doAcceptedForward = false;
        showRejected = false;
                
        system.debug('** -- whichAction = ' + whichAction + ' -- ***');
        system.debug('** -- CR = ' + customerRequestId + ' -- ***');
        system.debug('** -- V = ' + volunteerId + ' -- ***');
    }
    
    global PageReference doAction(){
        system.debug('*** -- into doAction function with ' + whichAction + ' and CR =  ' + customerRequestId + ' and V = ' + volunteerId + ' -- ***');
        PageReference pageRef;
        Customer_Requests__c cr = [select c.OwnerId, c.Allocated__c from Customer_Requests__c c where c.Id = :customerRequestId LIMIT 1];
        User volunteerUser = [select u.Id from User u where u.ContactId = :volunteerId and u.IsActive = true LIMIT 1];
        User gvtUser = [select u.Id from User u where u.Name = 'GVT' and u.IsActive = true LIMIT 1];
        Group gvtAdmin = [select g.Id, g.Name, g.DeveloperName from Group g where g.DeveloperName = 'GVT_Administrators' LIMIT 1];
        Contact volunteerContact = [select c.Id, c.OwnerId from Contact c where c.Id = :volunteerId LIMIT 1];
        RecordType crRT = [select r.Id from RecordType r where r.Name = :RT_CUSTOMER_REQUEST_PORTAL and r.isActive = true and r.SobjectType = 'Customer_Requests__c' LIMIT 1];
        CR_Notification__c crn = [Select c.Id, c.Volunteer__c, c.Status__c, c.Customer_Request__c, c.Date_Notification_Sent__c From CR_Notification__c c where 
                                    c.Volunteer__c = :volunteerId and
                                    c.Customer_Request__c = :customerRequestId and
                                    (c.Status__c != :CRN_STATUS_ACCEPTED or c.Status__c != :CRN_STATUS_REJECTED) ORDER BY c.Date_Notification_Sent__c DESC LIMIT 1];
        
        if (whichAction != null){
            if (RESPONSE_REJECT.equalsIgnoreCase(whichAction)){
                if (crn != null){
                    crn.Status__c = CRN_STATUS_REJECTED;
                    crn.Date_Responded__c = system.now();
                }
                showRejected = true;
                //pageRef = null;
                //What do we do on a reject?
            }else {
                system.debug('*** -- Into Accept -- ***');
                if (cr != null && volunteerUser != null){
                    system.debug('*** -- Found request and user -- ***');
                    if (!cr.Allocated__c){
                        system.debug('*** -- Request NOT Allocated yet -- ***');
                        cr.Allocated__c = true;
                        if (cr.OwnerId == gvtAdmin.Id){
                        	cr.Volunteer_Coordinator__c = gvtUser.Id;
                        }else {
                        	cr.Volunteer_Coordinator__c = cr.OwnerId;	
                        }
	                    cr.OwnerId = volunteerUser.Id;
                        if (crRT != null){
                            cr.RecordTypeId = crRT.Id;
                        }
                        cr.Assigned_Volunteer__c = volunteerContact.Id;
                        system.debug('*** -- About to update CR -- ***');
                        update cr;
                        system.debug('*** -- Set CRN status -- ***');
                        crn.Status__c = CRN_STATUS_ACCEPTED;
                        crn.Date_Responded__c = system.now();
                        doAcceptedForward = true;
                        system.debug('*** -- doAcceptedForward = ' + doAcceptedForward + ' -- ***');
                        openRequestURL = PORTAL_URL + cr.Id;
                        
                        //pageRef = new PageReference('https://uat-rnib-community-uat.cs17.force.com/' + cr.Id);
                        //pageRef.setRedirect(true);
                    }else {
                        system.debug('*** -- Request already Allocated - update CRN -- ***');
                        crn.Status__c = CRN_STATUS_ACCEPTED_NOT_AVAILABLE;
                        crn.Date_Responded__c = system.now();
                        alreadyAccepted = true;
                    }
                }
                //pageRef = new PageReference('https://uat-rnib-community-uat.cs17.force.com/' + cr.Id);        
            }
            system.debug('*** -- Update CRN -- ***');
            update crn;
        }
        
        return null;
    }
    
    @IsTest (seeAllData=true)
    private static void test1(){
        Profile saProfile = [select p.Id from Profile p where Name = 'System Administrator' LIMIT 1];
        Profile vProfile = [select p.Id from Profile p where Name = 'Community Login User - Volunteers' LIMIT 1];
        List<User>userList = [select u.Id from User u where u.IsActive = true and u.ProfileId = :saProfile.Id LIMIT 2];
        List<User>volunteerList = [select u.Id, u.ContactId from User u where u.ProfileId = :vProfile.Id and IsActive = true];
        Contact volunteerContact = TestUtilities.getContactRecord(volunteerList[0].ContactId);
        if (volunteerContact.FirstName == null) volunteerContact.FirstName = 'Test';
        if (volunteerContact.LastName == null) volunteerContact.LastName = 'Contact';
        if (volunteerContact.Email == null) volunteerContact.Email = volunteerContact.FirstName.toLowerCase() + '.' + volunteerContact.LastName.toLowerCase() + '@myemail.com';
        if (volunteerContact.MailingStreet == null) volunteerContact.MailingStreet = '123 Fake Street';
        if (volunteerContact.MailingCity == null) volunteerContact.MailingCity = 'London';
        if (volunteerContact.MailingState == null) volunteerContact.MailingState = 'London';
        if (volunteerContact.MailingPostalCode == null) volunteerContact.MailingPostalCode = 'EC12 1PR';
        if (volunteerContact.Phone == null) volunteerContact.Phone = '02071111111';
        update volunteerContact;
        
        User volunteerMgr = userList[0];
        User volunteerCoord = userList[1];
        RecordType standardRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_STANDARD);
        Role_Opportunity__c roleOpp = TestUtilities.getRoleOpportunity(TestUtilities.RT_STANDARD, standardRT.Id);
        roleOpp.Volunteer_Manager__c = volunteerMgr.Id;
        roleOpp.Volunteer_Coordinator__c = volunteerCoord.Id;
        roleOpp.Role_involve_working_with_Children__c = 'No';
        roleOpp.Number_of_References_Required__c = '2';
        roleOpp.Active_on_Website__c = true;
        roleOpp.Status__c = 'Approved';
        roleOpp.DBS_Check_required__c = 'DBS Standard';
        roleOpp.Vehicle_Check_Required__c = true;
        roleOpp.Risk_Assessment__c = true; 
        insert roleOpp;
        
        
        CustomerRequest obj = new CustomerRequest();
        obj.FirstName = 'Test';
        obj.LastName = 'LastName';
        obj.Phone = '013141';
        obj.MobilePhone = '013141';
        obj.Email = 'test@salesforce.com';
        obj.Street = 'Street1';
        obj.Street2 = 'Street2';
        obj.City = 'City';
        obj.Postcode = 'WD13 8DS';
        obj.Country = 'Test';

        obj.Activity = 'To Be Defined';
        obj.Description = 'Test';

        obj.isReferral = true;

        obj.referrallastname = 'Test';
        obj.referrallastname = 'LastNameReferrer';
        obj.referralorganisation = 'TestCompany';
        obj.adviseReferrer = true;
        obj.referralphone = '0189279';
        obj.referralemail = 'testreferral@salesforce.com';
        obj.referralstreet = 'Street1';
        obj.referralstreet2 = 'Street2';
        obj.referralcity = 'City';
        obj.referralpostcode = 'WD13 8DS';
        obj.referralcounty = 'Test';
    
        obj.save();
        
        Customer_Requests__c cr = obj.theRequest;
        
        CR_Notification__c crn = new CR_Notification__c();
        crn.Customer_Request__c = cr.Id;
        crn.Volunteer__c = volunteerContact.Id;
        insert crn;
        
        RecordType appRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_APPLICATION);
        Application__c application = new Application__c(RecordTypeId = appRT.Id);
        
        application.Applicant__c = volunteerContact.Id;
        application.Role__c = roleOpp.Id;
        
        insert application;
        
        
        PageReference testPage = Page.CustomerRequestResponse;
        testPage.getParameters().put('ACTION','Accept');
        testPage.getParameters().put('CR',cr.Id);
        testPage.getParameters().put('V',volunteerContact.Id);
        
        test.setCurrentPage(testPage);
        
        test.startTest();
        
        CustomerRequestResponseController crrc = new CustomerRequestResponseController();
        crrc.doAction();
        
        test.stopTest();
        
    }

}