src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Corporate_Account_Billing_City__c</fullName>
        <label>Corporate Account Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Billing_Country__c</fullName>
        <label>Corporate Account Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Billing_PostalCode__c</fullName>
        <label>Corporate Account Billing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Billing_State__c</fullName>
        <label>Corporate Account Billing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Billing_Street__c</fullName>
        <label>Corporate Account Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Name__c</fullName>
        <label>Corporate Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Account_Phone__c</fullName>
        <label>Corporate Account Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Active_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DBS_Check_required__c</fullName>
        <label>Criminal Record Check Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Access NI Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults and Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Check Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_References_Required__c</fullName>
        <inlineHelpText>Enter the number of references required in order to successfully apply for this role</inlineHelpText>
        <label>Number of References Required</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role_involve_working_with_Children__c</fullName>
        <label>Role Involves Working With Children?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent for approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_Check_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is a Driving License and Insurance Check required?  Note: This is a legal requirement for roles that involve driving.</inlineHelpText>
        <label>Driving Licence &amp; Vehicle Check Needed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <inlineHelpText>This is required for services like TSS</inlineHelpText>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <description>Corporate sector support such as partnerships, marketing initiatives and corporate events</description>
        <label>Corporate</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard volunteer opportunities (e.g. Admin, Befriending, Campaigning, CYF, ECLO, Fundraising, Technology, etc.)</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAccountCreation.cls
/**
* 2014-03-03 : SM : Test class to test the AccountCreation class
 */
@isTest (seeAllData=true)
private class TestAccountCreation {

    static testMethod void Test1() {
        //Test Data
        Profile saProfile = [select p.Id from Profile p where Name = 'System Administrator' LIMIT 1];
	 	Profile vProfile = [select p.Id from Profile p where Name = 'Community Login User - Volunteers' LIMIT 1];
	 	List<User>userList = [select u.Id from User u where u.IsActive = true and u.ProfileId = :saProfile.Id LIMIT 2];
	 	List<User>volunteerList = [select u.Id, u.ContactId from User u where u.ProfileId = :vProfile.Id and IsActive = true and u.ContactId != null];
	 	Contact volunteerContact = TestUtilities.getContactRecord(volunteerList[0].ContactId);
	 	if (volunteerContact.FirstName == null) volunteerContact.FirstName = 'Test';
	 	if (volunteerContact.LastName == null) volunteerContact.LastName = 'Contact';
	 	if (volunteerContact.Email == null) volunteerContact.Email = volunteerContact.FirstName.toLowerCase() + '.' + volunteerContact.LastName.toLowerCase() + '@myemail.com';
	 	if (volunteerContact.MailingStreet == null) volunteerContact.MailingStreet = '123 Fake Street';
	 	if (volunteerContact.MailingCity == null) volunteerContact.MailingCity = 'London';
	 	if (volunteerContact.MailingState == null) volunteerContact.MailingState = 'London';
	 	if (volunteerContact.MailingPostalCode == null) volunteerContact.MailingPostalCode = 'EC12 1PR';
	 	if (volunteerContact.Phone == null) volunteerContact.Phone = '02071111111';
	 	update volunteerContact;
	 	
	 	User volunteerMgr = userList[0];
	 	User volunteerCoord = userList[1];
	 	RecordType standardRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_STANDARD);
		Role_Opportunity__c roleOpp = TestUtilities.getRoleOpportunity(TestUtilities.RT_STANDARD, standardRT.Id);
		roleOpp.Volunteer_Manager__c = volunteerMgr.Id;
		roleOpp.Volunteer_Coordinator__c = volunteerCoord.Id;
		roleOpp.Role_involve_working_with_Children__c = 'No';
		roleOpp.Number_of_References_Required__c = '2';
		roleOpp.Active_on_Website__c = true;
		roleOpp.Status__c = 'Approved';
		roleOpp.DBS_Check_required__c = 'DBS Standard';
		roleOpp.Vehicle_Check_Required__c = true; 
		insert roleOpp;
		
		
		RecordType appRT = TestUtilities.getRecordTypeMap().get(TestUtilities.RT_APPLICATION);
		Application__c application = new Application__c(RecordTypeId = appRT.Id);
		
		application.Applicant__c = volunteerContact.Id;
		application.Role__c = roleOpp.Id;
		
		//Corporate Account information
		application.Corporate_Account_Name__c = 'Test Corporate Account';
		application.Corporate_Account_Phone__c = '01616161616';
		application.Corporate_Account_Billing_Street__c = '123 Fake Street';
		application.Corporate_Account_Billing_City__c = 'London';
		application.Corporate_Account_Billing_State__c = 'London';
		application.Corporate_Account_Billing_PostalCode__c = 'E12 4RR';
		application.Corporate_Account_Billing_Country__c = 'UK';
		
		
		insert application;
			
		system.debug('*** -- finished inserting all records - about to start test -- ***');
		test.startTest();
		
		AccountCreation ac = new AccountCreation();
		
		test.stopTest();
    }
}