src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <formula>&quot;See Opportunity Record&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <formula>Role__r.Role_Title__c</formula>
        <label>Role Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Role_Description__c</fullName>
        <inlineHelpText>Describe the Purpose and Aims of the role in a short, punchy paragraph.</inlineHelpText>
        <label>Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent for approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <inlineHelpText>This is required for services like TSS</inlineHelpText>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard volunteer opportunities (e.g. Admin, Befriending, Campaigning, CYF, ECLO, Fundraising, Technology, etc.)</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Donation__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <label>Volunteer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Donation</label>
    <nameField>
        <label>Time Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeDonationController.cls
/*
* 2014-04-04 : SM : TimeDonationController class.  Used on the TimeDonation VF page to offer extra functionality
*/
public with sharing class TimeDonationController {

    //final variables
    public final String TIME_DONATION_OBJECT_ID = '01Ib0000000TM8g';
    public final String EXPENSE_OBJECT_ID = '01Ib0000000TM8Y';
    public final String USER_TYPE_STANDARD = 'Standard';
    public final String USER_TYPE_GUEST = 'Guest';
    public final String USER_TYPE_PORTAL = 'CspLitePortal';
    public final String STATUS_ACTIVE = 'Active';

    //Check for logged in user
    public boolean isLoggedIn {
        get {
            if (isLoggedIn == null){
                if (!'GUEST'.equalsIgnoreCase(UserInfo.getUserType())){
                    isLoggedIn = true;
                }else {
                    isLoggedIn = false;
                }
            }
            return isLoggedIn;
        }
        set;
    }
    
    public List<Application__c> applist {get; set;}
    public User loggedInUser {get; set;}
    public Id selectedApplication {get; set;}
    public String applicationName {get; set;}
    public ApexPages.StandardController tdController {get; set;}
    public boolean isPortalUser {get; set;}
    public Contact portalContact {get; set;}
    public Time_Donation__c td {get; set;}
    
    //Constructor with standard controller from Time_Donation__c
    public TimeDonationController(ApexPages.standardController std){
        tdController = std;
        isPortalUser = false;
        td = (Time_Donation__c) std.getRecord();
        
        if (isLoggedIn){
            User loggedInUser = [select u.Id, u.ContactId, u.UserType from User u where u.Id = :UserInfo.getUserId() LIMIT 1];
            //Check user type if logged in to determine which Applications to return
            if (USER_TYPE_PORTAL.equalsIgnoreCase(UserInfo.getUserType())){
                isPortalUser = true;
                portalContact = [select c.Name, c.Id from Contact c where c.Id = :loggedInUser.ContactId LIMIT 1];
                td.Volunteer_Name__c = portalContact.Id;
                appList = [Select a.Applicant__r.Name, a.Volunteer_Manager__r.Name, a.Volunteer_Coordinator__r.Name, a.Status__c, a.Role__r.Name, a.Role_Title__c, a.Role_Description__c, a.Name, a.Id, a.Applicant__c From Application__c a where a.Applicant__c = :loggedInUser.ContactId and a.Status__c = :STATUS_ACTIVE];   
            }else {
                //appList = [Select a.Applicant__r.Name, a.Volunteer_Manager__r.Name, a.Volunteer_Coordinator__r.Name, a.Status__c, a.Role__r.Name, a.Role_Title__c, a.Role_Description__c, a.Name, a.Id, a.Applicant__c From Application__c a];
            }
        }
    }
    
    public PageReference save(){
        td.Volunteer_Role__c = selectedApplication;
        
        return tdController.Save();
        
    }
    
    //Save & New functionality
    public PageReference saveAndNew(){
        PageReference pageRef;
        
        tdController.save();
        
        pageRef = new PageReference('/setup/ui/recordtypeselect.jsp?ent=' + TIME_DONATION_OBJECT_ID);
        
        pageRef.setRedirect(true);
        
        return pageRef;
        
    }

}