src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <formula>Role__r.Role_Title__c</formula>
        <label>Role Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Role_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Technology Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Referee/CR Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>References Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruitment Checks Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Role Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable at Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Not Suitable for Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable References</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful - Unsuitable Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resigned from Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <displayFormat>Volunteer Role-{0000}</displayFormat>
        <label>Volunteer Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Role</fullName>
        <active>true</active>
        <description>This record type is when somebody is fulfilling a role or inactive in a role they were previously doing</description>
        <label>Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Volunteer</fullName>
        <active>true</active>
        <description>Use this record type for the volunteer</description>
        <label>Volunteer</label>
    </recordTypes>
</CustomObject>

src/objects/Customer_Requests__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <picklist>
            <controllingField>Service__c</controllingField>
            <picklistValues>
                <fullName>Changing settings for accessibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choosing or using a talking book player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installing broadband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installing software (e.g. JAWS, NVDA, Supernova, Zoomtext)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problems with broadband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problems with device or equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problems with software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setting up a new device or equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virus or spam issues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <formula>Customer_Name__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Requests</relationshipLabel>
        <relationshipName>Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Phone__c</fullName>
        <formula>Customer_Name__r.OtherPhone</formula>
        <label>Customer Other Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Time_Opened__c</fullName>
        <formula>CreatedDate</formula>
        <label>Date/Time Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referral_Contact_Name__c</fullName>
        <inlineHelpText>Only complete if the referral wants to know the outcome.</inlineHelpText>
        <label>Referral Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Requests (Referral Contact Name)</relationshipLabel>
        <relationshipName>Customer_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Technology Support</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - See RNIB Comments Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Customer Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Family__c</fullName>
        <label>Opportunity Family</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice Information and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending-Social Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children, Young People and Families</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Talking Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trusteeship and Advisory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RNIB_Group__c</fullName>
        <label>RNIB Group</label>
        <picklist>
            <picklistValues>
                <fullName>Action for Blind People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RNIB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff Institute for the Blind</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Service 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>This is the date that the opportunity is available from.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent for approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Coordinator__c</fullName>
        <inlineHelpText>This is required for services like TSS</inlineHelpText>
        <label>Volunteer Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Manager__c</fullName>
        <label>Volunteer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VolunteerLandingPageController.cls
public with sharing class VolunteerLandingPageController {
    public final String APP_STATUS_DRAFT = 'Draft';
    public final String APP_STATUS_SUBMITTED = 'Submitted';
    public final String APP_STATUS_PENDING_REFEREE_CHECKS = 'Pending Referee Checks';
    public final String APP_STATUS_PENDING_INTERVIEW = 'Pending Interviews';
    public final String APP_STATUS_SUCCESSFUL = 'Successful';
    public final String APP_STATUS_WITHDRAWN = 'Withdrawn';
    public final String APP_STATUS_UNSUCCESSFUL_ROLE_FILLED = 'Unsuccessful - Role Filled';
    public final String APP_STATUS_UNSUCCESSFUL_NOT_SUITABLE_AT_INTERVIEW = 'Unsuccessful - Not Suitable at Interview';
    public final String APP_STATUS_UNSUCCESSFUL_NOT_SUITABLE_FOR_INTERVIEW = 'Unsuccessful - Not Suitable for Interview';
    public final String APP_STATUS_UNSUCCESSFUL_UNSUITABLE_REFERENCES = 'Unsuccessful - Unsuitable References';
    public final String APP_STATUS_ACTIVE = 'Active';
    public final String APP_STATUS_INACTIVE = 'Inactive';
    public final String APP_STATUS_CONTACT_GVT = 'Contact GVT';
    public final String APP_STATUS_RESIGNED_FROM_ROLE = 'Resigned from Role';
    public final String APP_STATUS_UNSUCCESSFUL_UNSUITABLE_RISK_ASSESSMENT = 'Unsuccessful - Unsuitable Risk Assessment';
    
    public Map<String, String> appStatusMap {get; set;}

    
    
    public VolunteerLandingPageController(){
        appStatusMap = new Map<String, String>();
        appStatusMap.put(APP_STATUS_DRAFT,'Draft');
        appStatusMap.put(APP_STATUS_SUBMITTED,'Submitted');
        appStatusMap.put(APP_STATUS_PENDING_REFEREE_CHECKS,'In Progress');
        appStatusMap.put(APP_STATUS_PENDING_INTERVIEW,'In Progress');
        appStatusMap.put(APP_STATUS_SUCCESSFUL,'Successful');
        appStatusMap.put(APP_STATUS_WITHDRAWN,'Withdrawn');
        appStatusMap.put(APP_STATUS_UNSUCCESSFUL_ROLE_FILLED,'Closed');
        appStatusMap.put(APP_STATUS_UNSUCCESSFUL_NOT_SUITABLE_AT_INTERVIEW,'Closed');
        appStatusMap.put(APP_STATUS_UNSUCCESSFUL_NOT_SUITABLE_FOR_INTERVIEW,'Closed');
        appStatusMap.put(APP_STATUS_UNSUCCESSFUL_UNSUITABLE_REFERENCES,'Closed');
        appStatusMap.put(APP_STATUS_ACTIVE,'Active');
        appStatusMap.put(APP_STATUS_INACTIVE,'Inactive');
        appStatusMap.put(APP_STATUS_CONTACT_GVT,'In Progress');
        appStatusMap.put(APP_STATUS_RESIGNED_FROM_ROLE,'Resigned from Role');
        appStatusMap.put(APP_STATUS_UNSUCCESSFUL_UNSUITABLE_RISK_ASSESSMENT,'Closed');
    }
    private User user;
    //UAT Community ID
    //public final String GROUP_ID = '0F9g0000000CcnS';
    //LIVE Community ID
    public final String GROUP_ID = '0F9110000008Q5M';
    
    public final String COMMUNITY_ID = null;
    
    
    
    public List<ConnectAPI.FeedItem> getNewsFeedItems(){
        List<CollaborationGroup> cgList = new List<CollaborationGroup>();
        
        cgList = [select c.Id from CollaborationGroup c where c.Name = 'Volunteer Community' LIMIT 1];
        
        String groupId;
        
        if (cgList.size() > 0){
            groupId = cgList[0].Id;
        }else {
            groupId = GROUP_ID;
        }
        //return ConnectAPI.ChatterFeeds.getFeedItemsFromFeed(COMMUNITY_ID,ConnectApi.FeedType.Record,groupId).items;

        return ConnectAPI.ChatterFeeds.getFeedItemsFromFeed(COMMUNITY_ID, ConnectApi.FeedType.Record, groupId, 0, ConnectApi.FeedDensity.AllUpdates, null, 1, ConnectApi.FeedSortOrder.CreatedDateDesc).items;
    }
    
    public List<Customer_Requests__c> getCustomerRequests(){
        Id currentUserId = UserInfo.getUserId();
        List<Customer_Requests__c> customerRequests = [Select c.OwnerId, c.Id, c.Description__c, c.Customer_Phone__c, c.Customer_Name__c, c.Customer_Name__r.name,
                            c.Customer_Email__c, c.Allocated__c, c.Activity__c, c.Name, c.service__c, c.status__c, c.Date_Time_Opened__c, c.Referral_Contact_Name__r.Name, c.Closed__c From Customer_Requests__c c
                            where c.OwnerId = :currentUserId and c.Closed__c = false Order by c.Date_Time_Opened__c DESC];
        
        return customerRequests;
    }

    
    //2014-01-24 : SM : This new method is for the volunteer applications.  As we are returning ALL applications now, but with 'tailored' statuses
    //(See the appStatusMap above) we need to use a wrapper class rather than just the object.
    public List<ApplicationWrapper> getApplications(){
        List<ApplicationWrapper> appWrapperList = new List<ApplicationWrapper>();
        Id currentUserId = [select contactid from User where id = :UserInfo.getUserId()].contactid;

        RecordType roleRT = [select r.Id from RecordType r where r.Name = 'Application' and r.SobjectType = 'Application__c' LIMIT 1];

        for (Application__c a : [Select a.RecordType.id, a.Applicant__c, a.Applicant__r.Name, a.Role__r.Name, a.Role__r.id, a.status__c, a.start_date__c, a.Volunteer_Coordinator__r.Name, a.Service__c, a.Volunteer_Manager__r.Name, a.Role__r.RNIB_Group__c, a.Role__r.Opportunity_Family__c, a.Role_Title__c, a.application_status__c From Application__c a
                            where a.RecordType.id = :roleRT.id and a.Applicant__r.id = :currentUserId]){
                                ApplicationWrapper appWrapper = new ApplicationWrapper(a);
                                appWrapper.displayStatus = appStatusMap.get(a.Status__c);
                                appWrapperList.add(appWrapper);
                            }        
        return appWrapperList;
    }
    

    public List<Application__c> getCurrentRoles(){
        Id currentUserId = [select contactid from User where id = :UserInfo.getUserId()].contactid;

        RecordType roleRT = [select r.Id from RecordType r where r.Name = 'Role' and r.SobjectType = 'Application__c' LIMIT 1];

        List<Application__c> currentroles = [Select a.RecordType.id, a.Applicant__c, a.Applicant__r.Name, a.Role__r.Name, a.status__c, a.start_date__c, a.Volunteer_Coordinator__r.Name, a.Service__c, a.Volunteer_Manager__r.Name, a.Role__r.RNIB_Group__c, a.Role__r.Opportunity_Family__c, a.Role_Title__c From Application__c a
                            where a.RecordType.id = :roleRT.id and a.Applicant__r.id = :currentUserId and (a.status__c != 'Contact GVT' and a.status__c != 'Inactive')];
        
        return currentroles;
    }

    public User getUser() {
        return user;
    }

    public List<Role_Opportunity__c> getAvaliableOpportunities(){
        String soqlQuery = '';
        user = [SELECT id, contact.id, contact.Region__c, contact.Skills__c,contact.Areas_of_Interest__c FROM User WHERE id = :UserInfo.getUserId()];

        try { 
            soqlQuery = 'Select o.Role_Title__c, o.Active_on_Website__c, o.location__c, Interests__c, Role_Description__c From Role_Opportunity__c o where o.Active_on_Website__c = True';
            
            if (user.Contact.Region__c != null){
                soqlQuery += ' and o.Location__c includes (';
                String[] locSplit = user.Contact.Region__c.split(';');
                for (String s : locSplit){
                    soqlQuery += '\''+s+'\',';  
                }
                soqlQuery = soqlQuery.substring(0,soqlQuery.length()-1);
                soqlQuery += ')';
            }
            
            if (user.Contact.Areas_of_Interest__c != null){
                soqlQuery += ' and o.Interests__c includes (';
                String[] skillSplit = user.Contact.Areas_of_Interest__c.split(';');
                for (String s : skillSplit){
                    soqlQuery += '\''+s+'\',';  
                }
                soqlQuery = soqlQuery.substring(0,soqlQuery.length()-1);
                soqlQuery += ')';
            }
            soqlQuery += 'ORDER BY CreatedDate DESC LIMIT 5';
            
            List<Role_Opportunity__c> availableOpps;
            try {
                availableOpps = Database.query(soqlQuery);
            }catch (DMLException dmlEx){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There has been an error retrieving available Roles'));
            }
            
            
            return availableOpps;
        } 
            catch (Exception e) { 
            }
        return null;
    }
    
    public class ApplicationWrapper {
        
        public Application__c theApplication {get; set;}
        public String displayStatus {get; set;}
        
            public ApplicationWrapper(Application__c inApp){
                this.theApplication = inApp;
            }
    }

}