src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Areas_of_Interest__c</fullName>
        <inlineHelpText>Please select the areas of interest to you.  Note: updating this field will also update your interests in your profile</inlineHelpText>
        <label>Areas of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice Info and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending and Buddying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns and Lobbying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers and Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gardening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing, PR &amp; Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching, Training and Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trusteeship and Committee work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Work</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Data_Protection__c</fullName>
        <inlineHelpText>We will use your personal details in relation to your application and volunteering role.  Please indicate if you are happy to receive occasional information on other RNIB Group Volunteering opportunities</inlineHelpText>
        <label>Data Protection</label>
        <picklist>
            <picklistValues>
                <fullName>No Response</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked the person is on holiday or otherwise unavailable</inlineHelpText>
        <label>Unavailable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>If_Other__c</fullName>
        <label>If Other Format</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>If_Yes_Contact__c</fullName>
        <label>Technology required, If Yes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Access_Technology_Required__c</fullName>
        <label>Is Access Technology Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_communications_channel__c</fullName>
        <inlineHelpText>Enter the preferred method by which you would like to receive communications from RNIB here</inlineHelpText>
        <label>Preferred Communications Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_reading_correspondence_format__c</fullName>
        <inlineHelpText>Enter your preferred reading and correspondence format.  Note: updating this field in an application will also update your profile settings.</inlineHelpText>
        <label>Preferred Reading/Correspondence Format</label>
        <picklist>
            <picklistValues>
                <fullName>Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Braille</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear print (14 pt)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large print (16 pt)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Plain Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email HTML</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not known</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reasons_for_Wishing_to_Retire__c</fullName>
        <inlineHelpText>Enter the reasons the volunteer has given for wanting to retire as a volunteer with RNIB</inlineHelpText>
        <label>Reasons for Wishing to Retire</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Regions in which you are interested in Volunteering</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East of England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire/Humber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Request_to_Retire__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if the Volunteer has contacted you and wishes to retire as a Volunteer.  This request will be attended to by GVT</inlineHelpText>
        <label>Request to Retire</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Data_Protection__c</fullName>
        <inlineHelpText>We will use your personal details in relation to your application and volunteering role. Please indicate if you are happy to receive occasional information on other RNIB Group Volunteering opportunities</inlineHelpText>
        <label>Data Protection</label>
        <picklist>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unavailable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Communications_Channel__c</fullName>
        <label>Preferred Communications Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MyProfilePageController.cls
/* An apex class that keeps updates of a portal user in sync with its corresponding contact.
   Guest users are never able to access this page.
 */
public with sharing class MyProfilePageController {

    private User user;
    private boolean isEdit = false;

    public User getUser() {
        return user;
    }

    public MyProfilePageController() {
        user = [SELECT id, email, username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                street, city, country, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.firstName, contact.lastName,
                contact.MailingCity, contact.MailingCountry, contact.MailingPostalCode, contact.MailingState, contact.MailingStreet, contact.Phone, contact.HomePhone,
                contact.Preferred_reading_correspondence_format__c, contact.Preferred_communications_channel__c, contact.Reasons_for_Wishing_to_Retire__c, contact.Data_Protection__c, contact.Request_to_Retire__c,contact.Holiday__c, contact.Region__c, contact.MobilePhone, contact.OtherPhone, contact.Areas_of_Interest__c,
                contact.Is_Access_Technology_Required__c , contact.If_Yes_Contact__c, contact.If_Other__c
                FROM User
                WHERE id = :UserInfo.getUserId()];
        // guest users should never be able to access this page
        if (user.usertype == 'GUEST') {
            throw new NoAccessException();
        }
    }

    public Boolean getIsEdit() {
        return isEdit;
    }

    public void edit() {
        isEdit=true;
    }

    public void save() {
        if (user.contact != null) {
            //setContactFields(user.contact, user);
            setUserFields(user.contact, user);
        }

        try {
            if (user.contact != null){
                update user.contact;
            }
            
            update user;

            isEdit=false;
        } catch(DmlException e) {
            ApexPages.addMessages(e);
        }
    }

    public PageReference contactOnHoliday(){
        if (user.contact != null){
            user.contact.Holiday__c = true;
            update user.contact;
             user = [SELECT id, email, username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                street, city, country, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.firstName, contact.lastName,
                contact.MailingCity, contact.MailingCountry, contact.MailingPostalCode, contact.MailingState, contact.MailingStreet, contact.Phone, contact.HomePhone,
                contact.Preferred_reading_correspondence_format__c, contact.Preferred_communications_channel__c, contact.Reasons_for_Wishing_to_Retire__c, contact.Data_Protection__c, contact.Request_to_Retire__c,contact.Holiday__c, contact.Region__c, contact.MobilePhone, contact.OtherPhone, contact.Areas_of_Interest__c,
                contact.Is_Access_Technology_Required__c , contact.If_Yes_Contact__c, contact.If_Other__c
                FROM User
                WHERE id = :UserInfo.getUserId()];
        }
        return null;
    }
    
    public PageReference contactNotOnHoliday(){
        if (user.contact != null){
            user.contact.Holiday__c = false;
            update user.contact;
             user = [SELECT id, email, username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                street, city, country, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.firstName, contact.lastName,
                contact.MailingCity, contact.MailingCountry, contact.MailingPostalCode, contact.MailingState, contact.MailingStreet, contact.Phone, contact.HomePhone,
                contact.Preferred_reading_correspondence_format__c, contact.Preferred_communications_channel__c, contact.Reasons_for_Wishing_to_Retire__c, contact.Data_Protection__c, contact.Request_to_Retire__c,contact.Holiday__c, contact.Region__c, contact.MobilePhone, contact.OtherPhone, contact.Areas_of_Interest__c,
                contact.Is_Access_Technology_Required__c , contact.If_Yes_Contact__c, contact.If_Other__c
                FROM User
                WHERE id = :UserInfo.getUserId()];
        }
        return null;
    }

    public PageReference changePassword() {
        return Page.ChangePassword;
    }

    public void cancel() {
        isEdit=false;
         user = [SELECT id, email, username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                street, city, country, postalcode, state, localesidkey, mobilephone, extension, fax, contact.email, contact.firstName, contact.lastName,
                contact.MailingCity, contact.MailingCountry, contact.MailingPostalCode, contact.MailingState, contact.MailingStreet, contact.Phone, contact.HomePhone,
                contact.Preferred_reading_correspondence_format__c, contact.Preferred_communications_channel__c, contact.Reasons_for_Wishing_to_Retire__c, contact.Data_Protection__c, contact.Request_to_Retire__c,contact.Holiday__c, contact.Region__c, contact.MobilePhone, contact.OtherPhone, contact.Areas_of_Interest__c,
                contact.Is_Access_Technology_Required__c , contact.If_Yes_Contact__c, contact.If_Other__c
                
                FROM User
                WHERE id = :UserInfo.getUserId()];
    }

    public static void setContactFields(Contact c, User u) {
        c.title = u.title;
        c.firstname = u.firstname;
        c.lastname = u.lastname;
        c.email = u.email;
        c.phone = u.phone;
        c.mobilephone = u.mobilephone;
        c.fax = u.fax;
        c.mailingstreet = u.street;
        c.mailingcity = u.city;
        c.mailingstate = u.state;
        c.mailingpostalcode = u.postalcode;
        c.mailingcountry = u.country;
    }
    
    public static void setUserFields(Contact c, User u) {
        u.firstname = c.firstname;
        u.lastname = c.lastname;
        u.phone = c.phone;
        u.street = c.mailingstreet;
        u.city = c.mailingcity;
        u.state = c.mailingstate;
        u.postalcode = c.mailingpostalcode;
        u.country = c.mailingcountry;
    }
}