src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked the person is on holiday or otherwise unavailable</inlineHelpText>
        <label>Unavailable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>A person that has made one or more customer requests</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/CR_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Request__c</fullName>
        <label>Customer Request</label>
        <referenceTo>Customer_Requests__c</referenceTo>
        <relationshipLabel>Customer Request Notifications</relationshipLabel>
        <relationshipName>Customer_Request_Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted but no longer available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role_ID__c</fullName>
        <label>Volunteer Role ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <label>Customer Request Notification</label>
    <nameField>
        <displayFormat>CRN-{00000}</displayFormat>
        <label>Customer Request Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Request Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Request_Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <label>Primary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Request_Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Owner__c</fullName>
        <label>Secondary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Request_Assignment_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>To be defined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer Request Assignment Rule</label>
    <nameField>
        <displayFormat>CRAR-{0000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Request Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Requests__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Volunteer__c</fullName>
        <description>Lookup field to hold the assigned volunteer (community user) for the Customer Request</description>
        <label>Assigned Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Requests (Assigned Volunteer)</relationshipLabel>
        <relationshipName>Assigned_Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Requests</relationshipLabel>
        <relationshipName>Customer_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Post_Code__c</fullName>
        <formula>Customer_Name__r.MailingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Post Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Technology Support</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Ready for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - See RNIB Comments Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Hours_Donated_to_Resolve__c</fullName>
        <inlineHelpText>Enter the total amount of hours taken to fully complete the Customer Request</inlineHelpText>
        <label>Total Number of Hours Donated to Resolve</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Customer Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Time_Donation__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Enter the name of the Customer you are assisting here</inlineHelpText>
        <label>Customer/Group Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Request__c</fullName>
        <label>Customer Request</label>
        <referenceTo>Customer_Requests__c</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Name__c</fullName>
        <label>Volunteer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <label>Volunteer Role</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Time Donations</relationshipLabel>
        <relationshipName>Time_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Donation</label>
    <nameField>
        <label>Time Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Donations</pluralLabel>
    <recordTypes>
        <fullName>Individual_Time_Donation</fullName>
        <active>true</active>
        <description>Use this record type to create Time Donations for Individuals</description>
        <label>Individual Customer Time Donation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Donation_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Donated__c</fullName>
        <inlineHelpText>Enter the date when the time was donated</inlineHelpText>
        <label>Date Time Donated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TIme_Donation__c</fullName>
        <label>Time Donation</label>
        <referenceTo>Time_Donation__c</referenceTo>
        <relationshipLabel>Time Donation Entries</relationshipLabel>
        <relationshipName>Time_Donation_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Donated_in_Hours__c</fullName>
        <inlineHelpText>Enter time donated in whole hours (round-up to nearest hours donated)</inlineHelpText>
        <label>Time Donated in Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Donation Entry</label>
    <nameField>
        <displayFormat>TIME ENTRY - {00000}</displayFormat>
        <label>Time Donation Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Donation Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unavailable?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/CustomerRequestsTriggerClass.cls
/*
* 2014-01-14 : SM : New class to hold methods called from the CustomerRequestsTrigger
*/
public class CustomerRequestsTriggerClass {
    public static final String GVT_QUEUE_NAME = 'GVT Administrators';
    public static final String RT_INDIVIDUAL = 'Individual_Time_Donation';
    public static final String ACCEPTED_STATUS = 'Accepted';
    

    //This method will create a new Time Donation record, and an associated Time Donation Entry record if the Customer Request
    //Total_Number_of_Hours_Donated_to_Resolve__c is greater than 0 and the Customer Request is set to Closed - Approved
    public static void createTimeDonation(List<Customer_Requests__c> inRecords){
        
        RecordType timeDonationRT = [select r.Id, r.DeveloperName from RecordType r where r.SobjectType = 'Time_Donation__c' and r.DeveloperName = :RT_INDIVIDUAL and IsActive = true LIMIT 1];
        List<Time_Donation__c> newTDs = new List<Time_Donation__c>();
        Map<Id, Time_Donation__c> tdMap = new Map<Id, Time_Donation__c>();
        List<Time_Donation_Entry__c> newTDEs = new List<Time_Donation_Entry__c>();
        List<Time_Donation_Entry__c> updatedTDEs = new List<Time_Donation_Entry__c>();
        Map<String, Time_Donation__c> currentTDMap = new Map<String, Time_Donation__c>();
        Map<String, CR_Notification__c> crnMap = new Map<String, CR_Notification__c>();
        Set<String> tdNameList = new Set<String>();
        Set<Id> crIdSet = new Set<Id>();
        
        for (Customer_Requests__c cr : inRecords){
            String customerName = cr.Customer_Name__c;
            String tdName = cr.Name + ' ' + customerName.substring(0,15);
            crIdSet.add(cr.Id);
            tdNameList.add(tdName);
        }
        
        for (CR_Notification__c crn : [Select c.Volunteer_Role_ID__c, c.Status__c, c.Id, c.Customer_Request__c 
                                        From CR_Notification__c c where c.Customer_Request__c in :crIdSet and c.Status__c = :ACCEPTED_STATUS]){
            crnMap.put(crn.Customer_Request__c, crn);
        }
        
        for (Time_Donation__c td : [Select t.Customer_Request__c, t.Id, t.Name, (Select TIme_Donation__c, Date_Time_Donated__c, Time_Donated_in_Hours__c From Time_Donation_Entries__r) From Time_Donation__c t where t.Name in :tdNameList]){
            currentTDMap.put(td.Name, td);
        }
        
        for (Customer_Requests__c cr : inRecords){
            Time_Donation__c td;
            String customerName = cr.Customer_Name__c;
            String tdName = cr.Name + ' ' + customerName.substring(0,15);
            td = currentTDMap.get(tdName);
            if (td != null){
                tdMap.put(td.Customer_Request__c, td);
                Time_Donation_Entry__c tde = td.Time_Donation_Entries__r[0];
                if (tde.Time_Donated_in_Hours__c != cr.Total_Number_of_Hours_Donated_to_Resolve__c){
                    tde.Time_Donated_in_Hours__c = cr.Total_Number_of_Hours_Donated_to_Resolve__c;
                    updatedTDEs.add(tde);
                }
            }else {
                td = new Time_Donation__c(RecordTypeId = timeDonationRT.Id);
                td.Customer_Request__c = cr.Id;
                td.Name = cr.Name + ' ' + customerName.substring(0,15);
                td.Customer_Name__c = cr.Customer_Name__r.Name;
                td.Volunteer_Name__c = cr.Assigned_Volunteer__c;
                CR_Notification__c crn = crnMap.get(cr.Id);
                if (crn != null){
                    td.Volunteer_Role__c = crn.Volunteer_Role_ID__c;
                } 
                newTDs.add(td); 
            }
            
        }
        
        insert newTDs;
        
        for (Time_Donation__c td : newTDs){
            tdMap.put(td.Customer_Request__c, td);
        }
        
        //2014-09-11 : CSL : Changing this code slightly, to avoid the 'Null Pointer Exception' error
        for (Customer_Requests__c cr : inRecords){
            Time_Donation_Entry__c tde = new Time_Donation_Entry__c();
            Time_Donation__c td = tdMap.get(cr.Id);
            if (td != null){
                tde.Time_Donation__c = td.Id;
            }
            //tde.Time_Donation__c = tdMap.get(cr.Id).Id;
            tde.Time_Donated_in_Hours__c = cr.Total_Number_of_Hours_Donated_to_Resolve__c;
            newTDEs.add(tde);
        }
        
        insert newTDEs;
        
    }

    //This method will automatically assign the incoming Customer Request to the right Owner, based on Customer Request Assignment Rules
    public static void autoAssignCustomerRequest(List<Customer_Requests__c> inRequests){
        List<Id> primaryOwnerIdList = new List<Id>();
        List<Id> secondaryOwnerIdList = new List<Id>();
        Map<Id, User> primaryOwners = new Map<Id,User>();
        Map<Id, User> secondaryOwners = new Map<Id,User>();
        Id assignedUserId;
                
        Map<String, Customer_Request_Assignment_Rule__c> assignmentRulesMap = new Map<String, Customer_Request_Assignment_Rule__c>();
        for (Customer_Request_Assignment_Rule__c crar : [Select c.Service__c, c.Secondary_Owner__c, c.Primary_Owner__c, c.Post_Code__c, c.Id 
                                                            From Customer_Request_Assignment_Rule__c c]){
                                                                primaryOwnerIdList.add(crar.Primary_Owner__c);
                                                                secondaryOwnerIdList.add(crar.Secondary_Owner__c);
                                                                assignmentRulesMap.put(crar.Post_Code__c + '~' + crar.Service__c, crar);
                                                            }
        
        primaryOwners = new Map<Id, User>([select u.Id, u.Holiday__c from User u where u.Id in :primaryOwnerIdList]);
        secondaryOwners = new Map<Id, User>([select u.Id, u.Holiday__c from User u where u.Id in :secondaryOwnerIdList]);
        Group gvtQueue = [select g.Id, g.Name, g.Type from Group g where g.Name = :GVT_QUEUE_NAME and g.Type = 'Queue' LIMIT 1];    
        
        for (Customer_Requests__c cr : inRequests){
            String assignmentKey;
            if (cr.Customer_Post_Code__c != null){
                integer spaceInt = cr.Customer_Post_Code__c.indexOf(' ');
                String postCodeTrim = cr.Customer_Post_Code__c.substring(0,spaceInt).trim().toUpperCase();
                assignmentKey = postCodeTrim + '~' + cr.Service__c;
            }
            system.debug('*** -- assignmentKey = ' + assignmentKey + ' -- ***');
            if (assignmentKey != null){
                Customer_Request_Assignment_Rule__c crar = assignmentRulesMap.get(assignmentKey);
                if (crar != null){
                    User primaryUser = primaryOwners.get(crar.Primary_Owner__c);
                    User secondaryUser = secondaryOwners.get(crar.Secondary_Owner__c);
                    if (primaryUser != null){
                        if (!primaryUser.Holiday__c){
                            assignedUserId = primaryUser.Id;
                        }else {
                            if (secondaryUser != null){
                                if (!secondaryUser.Holiday__c){
                                    assignedUserId = secondaryUser.Id;
                                }
                            }
                        }
                    }else {
                        assignedUserId = gvtQueue.Id;
                    }
                    
                }else {
                    if (assignedUserId != null){
                        assignedUserId = gvtQueue.Id;
                    }
                }
                if (assignedUserId != null){
                    cr.OwnerId = assignedUserId;
                }
            }else {
                assignedUserId = gvtQueue.Id;
                cr.OwnerId = assignedUserId;
            }
            
        }   
        
            
    }       
    
}