src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Course_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Attend</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Course Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CoursesPageController.cls
public with sharing class CoursesPageController {
    
    public CoursesPageController() {
        
    }

    public List<Course_Booking__c> getCoursesBooking(){
        Id currentUserId = [select contactid from User where id = :UserInfo.getUserId()].contactid;

        List<Course_Booking__c> coursebooking = [Select c.id, c.Course__c, c.Person__c, c.Status__c, c.Course__r.id, c.course__r.Name, c.Course__r.Start_Date_Time__c, c.Course__r.End_Date_Time__c From Course_Booking__c c
                            where c.Person__r.id = :currentUserId and c.Status__c = 'Booked'];
        
        return coursebooking;
    }

    public List<Course_Booking__c> getCompleteCoursesBooking(){
        Id currentUserId = [select contactid from User where id = :UserInfo.getUserId()].contactid;

        List<Course_Booking__c> coursebooking = [Select c.id, c.Course__c, c.Person__c, c.Status__c, c.Course__r.id, c.course__r.Name, c.Course__r.Start_Date_Time__c, c.Course__r.End_Date_Time__c From Course_Booking__c c
                            where c.Person__r.id = :currentUserId and c.Status__c != 'Booked'];
        
        return coursebooking;
    }
}