src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Areas_of_Interest__c</fullName>
        <inlineHelpText>Please select the areas of interest to you.  Note: updating this field will also update your interests in your profile</inlineHelpText>
        <label>Areas of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice Info and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending and Buddying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns and Lobbying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers and Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gardening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing, PR &amp; Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching, Training and Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trusteeship and Committee work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Work</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>Regions in which you are interested in Volunteering</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East of England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire/Humber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact GVT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Course_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Attend</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Course Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCoursesPageController.cls
/*
* 2014-01-31 : KS : Test class for the CourseBookingController
 */
@isTest(SeeAllData=true)
public class TestCoursesPageController {

    static testMethod void testController() {
        Profile saProfile = [select p.Id from Profile p where Name = 'System Administrator' LIMIT 1];
        Profile vProfile = [select p.Id from Profile p where Name = 'Community Login User - Volunteers' LIMIT 1];
        List<User>userList = [select u.Id from User u where u.IsActive = true and u.ProfileId = :saProfile.Id LIMIT 2];
        List<User>volunteerList = [select u.Id, u.ContactId from User u where u.ProfileId = :vProfile.Id and IsActive = true];
        Contact volunteerContact = TestUtilities.getContactRecord(volunteerList[0].ContactId);
        if (volunteerContact.FirstName == null) volunteerContact.FirstName = 'Test';
        if (volunteerContact.LastName == null) volunteerContact.LastName = 'Contact';
        if (volunteerContact.Email == null) volunteerContact.Email = volunteerContact.FirstName.toLowerCase() + '.' + volunteerContact.LastName.toLowerCase() + '@myemail.com';
        if (volunteerContact.MailingStreet == null) volunteerContact.MailingStreet = '123 Fake Street';
        if (volunteerContact.MailingCity == null) volunteerContact.MailingCity = 'London';
        if (volunteerContact.MailingState == null) volunteerContact.MailingState = 'London';
        if (volunteerContact.MailingPostalCode == null) volunteerContact.MailingPostalCode = 'EC12 1PR';
        if (volunteerContact.Phone == null) volunteerContact.Phone = '02071111111';
        volunteerContact.Areas_of_Interest__c = 'Admin';
        volunteerContact.Region__c = 'North West';
        update volunteerContact;
        
        
        
        //insert Course1
        Course__c course1 = new Course__c(
        Name='Test Course 1'        
        );
        insert course1; 
        
        //insert Course2
        Course__c course2 = new Course__c(
        Name='Test Course 2'        
        );
        insert course2; 
        
        //insert Course Booking Booked
        Course_Booking__c coursebook = new Course_Booking__c(
        Person__c = volunteerContact.id,
        Course__c = course1.id,
        Status__c = 'Booked');
        insert coursebook;
        
        //insert Course Booking Attended
        Course_Booking__c courseatt = new Course_Booking__c(
        Person__c = volunteerContact.id,
        Course__c = course2.id,
        Status__c = 'Attended');
        insert courseatt;
        
        test.startTest();
        
        system.runAs(volunteerList[0]){
            CoursesPageController cbc = new CoursesPageController();
            //Course Booking Attending
            List<Course_Booking__c> coursebooking = cbc.getCoursesBooking();
            
            //Course Booking Attended
            List<Course_Booking__c> completecoursebooking = cbc.getCompleteCoursesBooking();
        }
        
        
        
        test.stopTest();
    }

}