src/objects/Corporate_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Corporate Accounts</relationshipLabel>
        <relationshipName>Corporate_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_PostalCode__c</fullName>
        <label>Billing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Corporate Account</label>
    <nameField>
        <label>Corporate Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CorporateAccountTriggerMethods.cls
public class CorporateAccountTriggerMethods {

	public static void processAccount(List<Corporate_Account__c> inRecords){
		List<String> accountNameList = new List<String>();
		
		for (Corporate_Account__c ca : inRecords){
			accountNameList.add(ca.Name);
		}
		
		Map<String, Account> accountMap = new Map<String, Account>();
		Map<String, Account> newAccountMap = new Map<String, Account>();
		
		for (Account a : [select a.Id, a.Name from Account a where a.Name in :accountNameList]){
			accountMap.put(a.Name, a);
		}
		
		for (Corporate_Account__c ca : inRecords){
			Account theAccount = accountMap.get(ca.Name);
			
			if (theAccount != null){
				ca.Account__c = theAccount.Id;
			}else {
				Account newAccount = new Account();
				newAccount.Name = ca.Name;
				newAccount.Phone = ca.Phone__c;
				newAccount.BillingStreet = ca.Billing_Street__c;
				newAccount.BillingCity = ca.Billing_City__c;
				newAccount.BillingState = ca.Billing_State__c;
				newAccount.BillingCountry = ca.Billing_Country__c;
				newAccount.BillingPostalCode = ca.Billing_PostalCode__c;
				if (!newAccountMap.containsKey(newAccount.Name)){
					newAccountMap.put(newAccount.Name, newAccount);
				} 
			}
		}
		
		insert newAccountMap.values();
	}

}