src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Active_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <inlineHelpText>Enter the times when the volunteers will be needed</inlineHelpText>
        <label>When Will You Be Needed?</label>
        <picklist>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun eve</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <inlineHelpText>Enter the number of volunteers you want to recruit for this opportunity</inlineHelpText>
        <label>How Many Volunteers Do You Need?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DBS_Check_required__c</fullName>
        <label>Criminal Record Check Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Access NI Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults and Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Check Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>today()+180</defaultValue>
        <inlineHelpText>This is the date that the opportunity is closed.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interests__c</fullName>
        <description>Information required for advertising on external websites and matching volunteer interests</description>
        <inlineHelpText>Information required for advertising on external websites and matching volunteer interests</inlineHelpText>
        <label>Type of Activity/Interests</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice Info and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending and Buddying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns and Lobbying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers and Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gardening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing, PR, Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching, Training and Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trusteeship and Committee work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Work</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>DBS_Check_required__c</controllingField>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East of England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire/Humber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Role_Description__c</fullName>
        <inlineHelpText>Describe the Purpose and Aims of the role in a short, punchy paragraph.</inlineHelpText>
        <label>Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Service 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Location__c</fullName>
        <inlineHelpText>Home based=volunteer based at home, Local area=out and about in local area, On site=RNIB Group premises, schools, care homes</inlineHelpText>
        <label>Where Based?</label>
        <picklist>
            <picklistValues>
                <fullName>Home Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Your Local Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleController.cls
public with sharing class RoleController {

    // the soql without the order and limit
    private String soql {get;set;}
    // the collection of contacts to display
    public List<Role_Opportunity__c> roles {get;set;}

  // the current field to sort by. defaults to last name
  public String sortField {
    get  { if (sortField == null) {sortField = 'location'; } return sortField;  }
    set;
  }

    // format the soql for display on the visualforce page
    public String debugSoql {
        get { return soql; }
        set;
    }

    // init the controller and display some sample data when the page loads
    public RoleController() {
        soql = 'select id, Active_on_Website__c, Availability__c, Capacity__c, DBS_Check_required__c, End_Date__c, Work_Location__c, Interests__c, Location__c, Role_Description__c, Role_Title__c, Service__c, Skills__c, Start_Date__c, Waiting_List__c, Role_Type__c from Role_Opportunity__c where Role_Title__c != null AND Active_on_Website__c= true ORDER BY CreatedDate DESC';
        runQuery();
    }

    // runs the actual query
    public void runQuery() {

        try {
            roles = Database.query(soql);
            } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unfortunately there is an error please try back later'));
        }
    }

    // runs the search with parameters passed via Javascript
    public PageReference runSearch() {

        String location = Apexpages.currentPage().getParameters().get('location');
        system.debug('*** -- location = ' + location + ' -- ***');
        String skills = Apexpages.currentPage().getParameters().get('skills');
        String availability = Apexpages.currentPage().getParameters().get('availability');
        system.debug('*** -- availability = ' + availability + ' -- ***');
        String home = apexpages.currentpage().getParameters().get('home');
        String interests = apexpages.currentpage().getParameters().get('interests');
        system.debug('*** -- interests = ' + interests + ' -- ***');
        String service = apexpages.currentpage().getParameters().get('service');
        String worklocation = apexpages.currentpage().getParameters().get('worklocation');

        soql = 'select id, Active_on_Website__c, Availability__c, Capacity__c, DBS_Check_required__c, End_Date__c, Work_Location__c, Interests__c, Location__c, Role_Description__c, Role_Title__c, Service__c, Skills__c, Start_Date__c, Waiting_List__c, Role_Type__c from Role_Opportunity__c where Role_Title__c != null AND Active_on_Website__c= true';
        if (!location.equals('')){
        	soql += ' and Location__c includes (';
        	String[] valSplit = location.split(',');
        	for (String s : valSplit){
        		soql += '\''+s+'\',';	
        	}
        	soql = soql.substring(0,soql.length()-1);
        	soql += ')';
        }
        //soql += ' and Location__c includes (\''+location+'\')';
        if (!availability.equals('')){
        	if ('FLEXIBLE'.equalsIgnoreCase(availability)){
        		//We don't need to filter on Availability if its Flexible
        	}else {
        		soql += ' and Availability__c includes (';
	        	String[] valSplit = availability.split(',');
	        	for (String s : valSplit){
	        		soql += '\''+s+'\',';	
	        	}
	        	soql = soql.substring(0,soql.length()-1);
	        	soql += ')';	
        	}
        	
        }
          
        if (!interests.equals('')){
        	soql += ' and Interests__c includes (';
        	String[] valSplit = interests.split(',');
        	for (String s : valSplit){
        		soql += '\''+s+'\',';	
        	}
        	soql = soql.substring(0,soql.length()-1);
        	soql += ')';
        }
        
        if (!worklocation.equals('')){
        	soql += ' and Work_Location__c LIKE \''+String.escapeSingleQuotes(worklocation)+'%\'';
        }
        
        soql += ' ORDER BY CreatedDate DESC';
        
		system.debug('*** -- soql = ' + soql + ' -- ***');
        // run the query again
        runQuery();

        return null;
    }

    // use apex describe to build the picklist values
    public List<String> locations {
        get {
            if (locations == null) {
                locations = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.Location__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                locations.add(f.getLabel());
            }
            return locations;          
        }
        set;
    }
    
    // use apex describe to build the picklist values
    public List<String> skills {
        get {
            if (skills == null) {
                skills = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.skills__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                skills.add(f.getLabel());
            }
            return skills;          
        }
        set;
    }

    // use apex describe to build the picklist values
    public List<String> availability {
        get {
            if (availability == null) {
                availability = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.Availability__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                availability.add(f.getLabel());
            }
            return availability;          
        }
        set;
    }

    // use apex describe to build the picklist values
    public List<String> interests {
        get {
            if (interests == null) {
                interests = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.interests__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                interests.add(f.getLabel());
            }
            return interests;          
        }
        set;
    }

    // use apex describe to build the picklist values
    public List<String> service {
        get {
            if (service == null) {
                service = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.service__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                service.add(f.getLabel());
            }
            return service;          
        }
        set;
    }

    // use apex describe to build the picklist values
    public List<String> worklocation {
        get {
            if (worklocation == null) {
                worklocation = new List<String>();
                Schema.DescribeFieldResult field = Role_Opportunity__c.Work_Location__c.getDescribe();
                for (Schema.PicklistEntry f : field.getPicklistValues())
                worklocation.add(f.getLabel());
            }
            return worklocation;          
        }
        set;
    }

}