src/objects/Role_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Active_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <inlineHelpText>Enter the times when the volunteers will be needed</inlineHelpText>
        <label>When Will You Be Needed?</label>
        <picklist>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mon eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tues eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wed eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thurs eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fri eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sat eve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun eve</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <inlineHelpText>Enter the number of volunteers you want to recruit for this opportunity</inlineHelpText>
        <label>How Many Volunteers Do You Need?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DBS_Check_required__c</fullName>
        <label>Criminal Record Check Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Access NI Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access NI Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS Enhanced check for regulated activity with adults and children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Scotland Adults and Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Check Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>today()+180</defaultValue>
        <inlineHelpText>This is the date that the opportunity is closed.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interests__c</fullName>
        <description>Information required for advertising on external websites and matching volunteer interests</description>
        <inlineHelpText>Information required for advertising on external websites and matching volunteer interests</inlineHelpText>
        <label>Type of Activity/Interests</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice Info and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Befriending and Buddying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns and Lobbying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers and Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment and Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gardening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing, PR, Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching, Training and Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trusteeship and Committee work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Work</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>DBS_Check_required__c</controllingField>
            <picklistValues>
                <fullName>North West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Midlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East of England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yorkshire/Humber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Role_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Service 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <inlineHelpText>Skills and Experience which are required for the Role</inlineHelpText>
        <label>What Skills/Experience Are Needed?</label>
        <picklist>
            <controllingField>Opportunity_Family__c</controllingField>
            <picklistValues>
                <fullName>Ability to ask questions sensitively</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to communicate clearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to find innovative solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to listen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to listen to others ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to take instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to use your own initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Able to prioritise tasks and be flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Able to run about 200 metres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Able to use own initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Able to work unsupervised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A caring and friendly nature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to phone, e-mail &amp; internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurately/fluently read materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurate typing at a reasonable speed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A flexible approach to the role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A good communicator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A knowledge of general admin practices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A listening ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A natural empathy with people</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>An interest in technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>An interest in technology innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A pleasant telephone manner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approachable &amp; empathetic nature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approachable telephone manner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A reliable and conscientious attitude</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ask for help and receive supervision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attention to detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness of other Assistive Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A welcoming and friendly nature</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>This is the date that the opportunity is available from.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waiting_List__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If the role receives applications over your stated capacity, do you want them added to a waiting list for future recruitment?</inlineHelpText>
        <label>Waiting List</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunities</label>
    <nameField>
        <displayFormat>Opportunity -{0000}</displayFormat>
        <label>Role Opp ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard volunteer opportunities (e.g. Admin, Befriending, Campaigning, CYF, ECLO, Fundraising, Technology, etc.)</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleControllerTest.cls
@isTest
private class RoleControllerTest {

    static testMethod void RoleControllerTest() {

        date startdate = date.today();
        date enddate = date.today().addDays(30);

        //Create a Test Role Record
        Role_Opportunity__c Role = new Role_Opportunity__c();
            Role.Active_on_Website__c = TRUE;
            Role.Availability__c = 'Monday Mornings';
            Role.Capacity__c = 10;
            Role.DBS_Check_required__c = 'DBS Standard';
            Role.End_Date__c = startdate;
            Role.Interests__c = 'Playground';
            Role.Role_Title__c = 'Test Role';
            Role.Service__c = 'Service 1';
            Role.Skills__c = 'Attention to detail';
            Role.Start_Date__c = enddate;
            Role.Waiting_List__c = TRUE;
            Role.Location__c = 'North West';
            Role.Work_Location__c ='Home';
            Role.Number_of_References_Required__c = '2';
        insert Role;

        PageReference pg = Page.Roles;
            Test.setCurrentPage(pg);
                pg.getParameters().put('skills', 'Attention to detail');
                pg.getParameters().put('availability', 'Monday Mornings');
                pg.getParameters().put('interests', 'Playground');
                pg.getParameters().put('service', 'Service 1');  
                pg.getParameters().put('location', 'North West');   
                pg.getParameters().put('worklocation', 'Home' );

        RoleController controller=new RoleController();
            System.assertequals (controller.sortField, 'location');
            System.assert(controller.runSearch() == null);

        String testDebugSoql = controller.debugSoql;

        List<String> testlocations = new List<String>();
        testlocations = controller.locations;
        System.assertequals (testlocations[0], 'North West');

        List<String> testavailability = new List<String>();
        testavailability = controller.availability;
        System.assertequals (testavailability[0], 'Flexible');

        List<String> testinterests = new List<String>();
        testinterests = controller.interests;
        System.assertequals (testinterests[0], 'Admin');

        List<String> testservice = new List<String>();
        testservice = controller.service;
        System.assertequals (testservice[0], 'Service 1');

        List<String> testskills = new List<String>();
        testskills = controller.skills;
        System.assertequals (testskills[0], 'Ability to ask questions sensitively');
        
        List<String> testworklocation = new List<String>();
        testworklocation = controller.worklocation;
        System.assertequals (testworklocation[0], 'Home Based');        

        controller.sortField = 'Some invalid sort field';
        controller.runQuery();

    }

}